variables:
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -Dtycho.localArtifacts=ignore -Dmaven.repo.local=.m2/repository -f build/pom.xml -s build/settings.xml"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository

stages:
  - build
  - test
  - analyze
  - deploy
  - post-deploy

build:
  # build plugin using Maven
  image: maven:3-jdk-11
  stage: build
  script:
    - mvn ${MAVEN_CLI_OPTS} clean package -P build,site
  artifacts:
    expire_in: 4 weeks
    when: always
    paths:
      - org.mard.dt.editing.repository/target/repository*.zip
      - org.mard.dt.editing.repository/target/repository/*
      - "*/target/results"
      - "*/target/jacoco*.exec"
      - "*/target/site/jacoco"
      - "*/target/jacoco*"

pages:
  stage: deploy
  script:
    - mkdir -p ./public/update
    - mv -f ./org.mard.dt.editing.repository/target/repository/* ./public/update
    - mv -f ./org.mard.dt.editing.repository/target/repository-*-SNAPSHOT.zip ./public
  dependencies:
    - build
  environment:
    name: pages
    url: "${CI_PAGES_URL}"
  artifacts:
    paths:
      - public
  only:
    - master@marmyshev/edt-editing
